### ISSUE TITLE
楼主帮忙看看 from pcbeta

### ISSUE THREAD

**Issue by juenuo** [QiuChenly/Parallels#1]
[*] Copy prl_disp_service
[*] Sign prl_disp_service
/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: replacing existing signature
[*] Copy fake licenses.json
[*] Start Parallels Service
[*] Exit Parallels Desktop account ...
Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm18_zh_CN_249).
[*] Disable CEP ...
Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm18_zh_CN_249).
Login failed: Unable to connect to Parallels Service. Make sure that the prl_disp_service process is active and it is not blocked by Firewall. For details, please refer to this knowledgebase article (https://www.parallels.com/products/desktop/supportinfo/pdfm18_zh_CN_249).

**Comment by juenuo** [comment]
折腾两天，各种提示: prl_disp_service这个服务没起来，网上试过所有能试的办法了 还是不行

**Comment by QiuChenly** [comment]
不需要管它。。。破解已经完成了，直接打开pd就激活了

**Comment by juenuo** [comment]
我也想这样，现在是以装好虚拟机先不破解啥，直接打开提示无法连接prl_disp_service服务

**Comment by QiuChenly** [comment]
卸载重装 然后直接激活
