### ISSUE TITLE
18.1.0 m1 pro 无法使用

### ISSUE THREAD

**Issue by asumi233** [QiuChenly/Parallels#2]
RT,x86测试过没问题 arm的 无法激活

**Comment by miscwork** [comment]
Same here


chmod +x ./install.sh && sudo ./install.sh
[*] Copy prl_disp_service
[*] Sign prl_disp_service
/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: replacing existing signature
[*] Copy fake licenses.json
[*] Start Parallels Service
[*] Exit Parallels Desktop account ...
Unable to sign out: Unable to sign out. Please check the Internet connection and try again.
[*] Disable CEP ...
Involved 'set' command option is available only in Parallels Desktop for Mac Pro or Business Edition.
[*] Crack over

**Comment by miscwork** [comment]
ARM (Mac mini M1)

**Comment by QiuChenly** [comment]
> RT,x86测试过没问题 arm的 无法激活

1925374620 qq联系我检查一下

**Comment by QiuChenly** [comment]
> Same here
> 
> chmod +x ./install.sh && sudo ./install.sh [_] Copy prl_disp_service [_] Sign prl_disp_service /Applications/Parallels Desktop.app/Contents/MacOS/Parallels Service.app/Contents/MacOS/prl_disp_service: replacing existing signature [_] Copy fake licenses.json [_] Start Parallels Service [_] Exit Parallels Desktop account ... Unable to sign out: Unable to sign out. Please check the Internet connection and try again. [_] Disable CEP ... Involved 'set' command option is available only in Parallels Desktop for Mac Pro or Business Edition. [*] Crack over

1925374620 use Tencent QQ find me for help you

**Comment by bbZCat** [comment]
same here. is there any solutions?

**Comment by QiuChenly** [comment]
> same here. is there any solutions?

please contact with me use Remote Help Tools(e.g. ToDesk) to resolve this questions. you can download it at https://www.todesk.com/ , and my telegram id is @QIuChenly : https://t.me/QiuChenly
