### ISSUE TITLE
update

### ISSUE THREAD

**Issue by iaihc** [QiuChenly/Parallels#3]
update

**Comment by bunduuk** [comment]
+1 pls

**Comment by QiuChenly** [comment]
already update for 18.3.

**Comment by Cowboy-Shuai** [comment]
> 已经更新了 18.3。

18.3 的是不是不能在M1上用？

**Comment by iaihc** [comment]
经测试，不可用，程序死掉了，不可用。




江波
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QiuChenly/Parallels"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 凌晨1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [QiuChenly/Parallels] update (Issue #3)





  
已经更新了 18.3。
  
18.3 的是不是不能在M1上用？
