### ISSUE TITLE
Apple ID Sign in Problem

### ISSUE THREAD

**Issue by pettigrew1** [QiuChenly/Parallels#4]
Hello @QiuChenly 

How can I solve Apple ID signin problem on guest MacOS VMs?

Thanks

**Comment by QiuChenly** [comment]
what's u mean's...?i don't known about u say ' solve Apple ID signin problem ' on guest MacOS VMs?

**Comment by pettigrew1** [comment]
@QiuChenly you cannot login your Apple account in MacOS virtual machines
You get a similar error like:
https://softantenna.com/blog/mac-icloud-this-action-could-not-be-completed/

**Comment by pettigrew1** [comment]
Also check this link please https://forum.parallels.com/threads/use-apple-id-in-macos-vm-on-apple-m-series-mac.355381/
